### ISSUE TITLE
Could deabsdeep replace backslashes with slashes on Windows ?

### ISSUE THREAD

**Issue by elevatebart** [sapegin/deabsdeep#2]
When running styleguidist tests on windows we get abunch of failures.
Could deabsdeep (on windows only) replace \ with / in managed path ?

**Comment by elevatebart** [comment]
BTW I am already prepping a PR for that.

**Comment by sapegin** [comment]
Do you mean this line?

https://github.com/sapegin/deabsdeep/blob/645b68ab3899bb28ba79661317ebe7311dd4b4cc/src/getRootDir.js#L12

**Comment by elevatebart** [comment]
yes, adding a `.replace(/\\/, '/')` at the end
